services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newadv
    volumes:
      - newadv_pg:/var/lib/postgresql/data

volumes:
  newadv_pg: